name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: README.md
        config_file: "markdown-lint-check-config.json"
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: "markdown-link-check-config.json"
